### ISSUE TITLE
object varible or with block variable not set

### ISSUE THREAD

**Issue by lsattf** [Aeroanion/MeasureXForm-Solidworks-Macro#3]

**Comment by Aeroanion** [comment]
@lsattf , when did the error occur? Was it as soon as the macro started or when you selected a frame? Are there any other details of the error that you can provide for me?

**Comment by lsattf** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/58330520/107121961-13651080-688d-11eb-8fc5-fa73dbb7fadc.png)
Hi, here is the error screenshot

**Comment by lsattf** [comment]
It is solidworks 2019

**Comment by Aeroanion** [comment]
@lsattf, I finally started having the issue that you described. Sorry that it took so long. My newest commit fixes it.
I'll tag a new release as well.
